# Generated by Django 4.2.7 on 2023-12-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='project_manager',
        ),
    ]
